# Airflow Webserver
  airflow-webserver:
    image: apache/airflow:latest
    ports:
      - "8080:8080"
    volumes:
      - airflow-data:/usr/local/airflow
    depends_on:
      - influxdb
    networks:
      - mining-network

  # Airflow Scheduler
  airflow-scheduler:
    image: apache/airflow:latest
    volumes:
      - airflow-data:/usr/local/airflow
    depends_on:
      - influxdb
    networks:
      - mining-network

  # Nginx
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
    networks:
      - mining-network

